require:
  - rubocop-rails
  - rubocop-performance

#inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Layout/IndentationWidth:
  Width: 4

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'
