services:
  # Service for the Ruby on Rails web application
  web:
    user: "${UID}:${GID}"
    build: .
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/progrando
      RAILS_ENV: development
    tty: true
    stdin_open: true

  # Service for the MariaDB database
  db:
    image: mariadb:11.5.2  # Version spécifique pour plus de stabilité
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: progrando
      MYSQL_USER: progrando  # Optionnel: utilisateur dédié
      MYSQL_PASSWORD: password  # Optionnel: mot de passe utilisateur
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data: