version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=mysql2://root:${DB_PASSWORD}@db:3306/progrando_production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./public/assets:/app/public/assets  # Ajoutez cette ligne
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=progrando_production
    restart: unless-stopped
    ports:
      - "3306:3306"
volumes:
  mariadb_data:
